### PR TITLE
Add missing bustpointtounderbust.svg.

### PR DESCRIPTION
**Pull request by nicholasdower**
I noticed this file was missing while adding some measurements:
image

I took a shot at creating one by copying an existing image and modifying the path. I would love to hear any suggestions for how this should actually look. Here is a screenshot of my image:
image

Note that I wasn't able to find a reliable SVG editor that worked well with the files in this repo. I tried Inkscape and macSVG but couldn't get either to edit the paths. ~~I also wasn't able to get this repo running locally so I can't say with any confidence that this works on the actual site. I will ask for help on Discord.~~ (had to run `ln -s ../freesewing monorepo`)

### CODE REVIEW

**Comment by nicholasdower** [comment]
I got freesewing.org running after all and this doesn't seem to be working:
image

**Comment by nicholasdower** [comment]
Never mind. I just needed to add it to index.js:
image

**Comment by nicholasdower** [comment]
Just noticed the "without breasts" option is available. Still working on this but think I just need to add it to `breastsOnly` in `src/components/measurements/images.js`.

**Comment by joostdecock** [comment]
> I wonder whether I should also add it to src/components/model-graph.js and src/components/person/measurements-order.js...

If memory serves me well, those are dead code that is no longer used.
I'd remove it, but we're building a new site altogether so I'm not too bothered.

As for this PR. It's great. For SVG editors, I'm rather used to hand-writing SVGs by now :joy:

**Comment by joostdecock** [comment]
@nicholasdower Check your mailbox for an organisation invite. Should have done that last time, but I forgot.

**Comment by joostdecock** [comment]
Deploy is ongoing: https://app.netlify.com/teams/freesewing/builds/61dd7afcc3c79500076e3fe7

**Comment by nicholasdower** [comment]
> @nicholasdower Check your mailbox for an organisation invite. Should have done that last time, but I forgot.

Received and accepted. Thank you!

**Comment by nicholasdower** [comment]
> > I wonder whether I should also add it to src/components/model-graph.js and src/components/person/measurements-order.js...
> 
> If memory serves me well, those are dead code that is no longer used. I'd remove it, but we're building a new site altogether so I'm not too bothered.

Understood. Also saw all the great info on Discord. Thanks for the help.

> 
> As for this PR. It's great. For SVG editors, I'm rather used to hand-writing SVGs by now 😂

😄

**Pull request merged**
