### PR TITLE
chore: Add @stoffsuchti as contributor

### PR DESCRIPTION
**Pull request by joostdecock**
This commit will add you to the contributors file.
The result is that you will be listed on the website as a contributor.
For this reason, you should approve this before this gets
merged.

In other words, this commit is the papertrail for the opt-in way of
adding contributors to the site.

### CODE REVIEW

**Comment by joostdecock** [comment]
👋 @stoffsuchti this is still open. Please let me know today because the release is planned for tomorrow.

**Comment by stoffsuchti** [comment]
What does this mean?

**Comment by joostdecock** [comment]
We've made some changes to our website, including listing the contributors: https://next.freesewing.org/community/who/
This is on an opt-in basis, so we only add people if they sign off on that.

This merge request would add you, but only if you approve it or leave a comment to let us know that is ok.
If not, we can close it and move on

**Comment by stoffsuchti** [comment]
You can mention me by my Nickname "Stoffsuchti". No Real Name.

**Pull request merged**
