### PR TITLE
chore: Add @AlfaLyr as a contributor

### PR DESCRIPTION
**Pull request by joostdecock**
This commit will add @AlfaLyr to the contributors file.
The result is that she will be listed on the website as a contributor.
For this reason, @AlfaLyr should approve this before this gets
merged.

In other words, this commit is the papertrail for the opt-in way of
adding contributors to the site.

### CODE REVIEW

**Comment by joostdecock** [comment]
Sorry, I accidentally let some unrelated changes slip into this PR. I've removed them afterwards.

The point of this PR is to add @AlfaLyr to the freesewing.org website as a contributor. 
She already is a contributor, this will just make her be listed as one on the site.

Since we only list contributors who opt-in, this PR is a way to get that approval. If @AlfaLyr approves this pull request, we will merge it. If she does not, we will not merge it, and she will not be listed as a contributor.

I hope she'll approve it though :slightly_smiling_face:

**Comment by joostdecock** [comment]
Thank you :slightly_smiling_face:

**Comment by AlfaLyr** [comment]
Sure I approve! I know I'm a bit absent lately, but I'm super busy and I can't take as much care of Freesewing as I would like, but I'm still here :)

**Comment by joostdecock** [comment]
No worries. Out of sight is not out of heart :hugs:

**Pull request merged**
