### PR TITLE
test

### PR DESCRIPTION
**Pull request by nadege**

### CODE REVIEW

**Comment by joostdecock** [comment]
Perhaps I can give some background to the changes that were made recently.
Most of the changes are in the site structure under `/account/`. Specifically how we handle `people` and `patterns` in a user's account.

We used to have urls like `/patterns/handle` and then on that page we had to figure out whether this is a pattern that belongs to the user themselves, or is this a pattern another user shared. The lead to a good deal of complexity in that page to handle both scenarios.

Now, when you go to `/patterns/handle` (obviously `handle` is a 5-character ID of the pattern), we treat it as somebody else's pattern. That means we load it from the backend, and don't show options that are exclusive to your own pattern.

When you go to `/account/patterns/handle` we treat it as your own pattern. So no need to get it from the backend, it's available in local storage in the user's account, so we can skip the async code. on this page, you have options that are limited to your own patterns.

It also allows us to build a tree-like structure in the navigation menu that lists all the user's (own) patterns and the relevant links under them.

I hope this helps a bit :)

**Comment by nadege** [comment]
Oh I was playing with cypress. :grin: 
The tests in `people.spec.js` fail on the line with `i18n["app.someid"]` 
because `i18n` not defined. I was trying to understand how translation work by printing some logs in the tests, but that doesn't seems to work here (with `cy.log(...)`).
"print debugging" is not great anyway I should setup a better local env where I can run cypress. :grin: 

Thank you for the explanations about patterns though! This will definitely be useful :)

**Comment by joostdecock** [comment]
No worries, play all you want :) Just wanted to try give some explanations on the kind of things that are not documented (because who would read them) but might make it easier to break in to the project.

For internationalization, we use [reactl-int](https://formatjs.io/docs/react-intl/). It's typically used with a react component like this:

```js
import { FormattedMessage } from 'react-intl'
//...
<FormattedMessage id='account.newsletterTitle' />
```

Sometimes however, you just want the translated string (like for `alt` or `title` attributes).
For this, we provide the `app.translate` helper method (in the `app` object that sort of ties the entire frontend together.

```js
import useApp from '../hooks/useApp'
//...
const app = useApp()
console.log(app.translate('account.newsletterTitle'))
```
The IDs to use in translation are from https://github.com/freesewing/freesewing/tree/develop/packages/i18n/src/locales/en

**Comment by joostdecock** [comment]
Closing this as it just sits here

**Pull request closed without merging**
